spring:
  datasource:
    url: jdbc:mysql://139.199.185.175:3306/reptile?useUnicode=true&characterEncoding=utf-8
    username: root
    password: '!@#$%^&*()Tucxx2019'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  path: logs

reptile:
  read-time: 2019-04-17
  account: 13428889873
  password: Will87200407
  count-limit: 3