spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reptile?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root@11
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  path: logs

config:
  reptile:
    read-time: 2019-04-26
    count-limit: 3

  cowlevel:
    account: 13428889873
    password: Will87200407
    login-url: https://cowlevel.net/passport/login/submit
    type-url: https://cowlevel.net/following/element-data
