spring.context
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reptile?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root@11
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  path: logs

reptile:
  read-time: 2019-4-10
  account: 314713228@qq.com
  password: a123456