spring:
  datasource:
    url: jdbc:mysql://localhost:3306/reptile?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Root@11
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  path: logs