spring:
  datasource:
    url: jdbc:mysql://139.199.185.175:3306/reptile?useUnicode=true&characterEncoding=utf-8
    username: root
    password: '!@#$%^&*()Tucxx2019'
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
logging:
  path: logs

reptile:
  read-time: 2019-03-01
  account: 314713228@qq.com
  password: a123456